### Site settings

name: Ross Kippenbrock

# Short bio or description (displayed in the header)
description: Software Engineer in Brooklyn, NY

avatar: https://avatars1.githubusercontent.com/u/5350074?v=2&s=460

footer-links:
  email: rkippenbrock@gmail.com
  github: rkipp1210
  instagram: rkipp1210
  linkedin: rosskippenbrock
  twitter: RossKipp

google_analytics: UA-53642574-1

disqus: rkipp1210

### Config

markdown: kramdown
highlighter: rouge
permalink: /:title

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!


### Build settings

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
