### Site settings

name: Ross Kippenbrock

description: Software Engineer in Brooklyn, NY

avatar: https://avatars1.githubusercontent.com/u/5350074?v=2&s=460

footer-links:
  email: rkippenbrock@gmail.com
  github: rkipp1210
  instagram: rkipp1210
  linkedin: rosskippenbrock
  twitter: RossKipp

google_analytics: UA-53642574-1

disqus: rkipp1210

### Config

markdown: kramdown
highlighter: rouge
permalink: /:title

sass:
  sass_dir: _scss
  style: :expanded

# plug-ins
gems:
  - jemoji


### Build settings

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
